/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Cursor;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author macarena
 */
public class LoginView extends javax.swing.JFrame {

    public static final String urlDB = "jdbc:mysql://localhost:3306/usuarios";

    public LoginView() {
        initComponents();
        setFrame();
    }

    private void setFrame() {
        //D:\Primero-DAM\Programacion JAVA\EjercicioLogin\src\main\java\gf\local\Ejemplo\login\images\aceptar.png
        botonAceptar.setIcon(new javax.swing.ImageIcon(("./src/main/java/gf/local/Ejemplo/login/images/aceptar.png")));
        botonCancelar.setIcon(new javax.swing.ImageIcon(("./src/main/java/gf/local/Ejemplo/login/images/cancelar.png")));
        BtnShowPass.setIcon(new javax.swing.ImageIcon(("./src/main/java/gf/local/Ejemplo/login/images/ojo.jpg")));
        BtnShowPass1.setIcon(new javax.swing.ImageIcon(("./src/main/java/gf/local/Ejemplo/login/images/ojo.jpg")));
        this.labelRegistro.setText("<HTML> <FONT color=\"#000099\"><U>¿Todavía no te has registrado?</U></FONT> </HTML>");
        this.labelRegistro.setToolTipText("Pulsa para registrarte");
        this.labelRegistro.setCursor(new Cursor(Cursor.HAND_CURSOR));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        botonCancelar = new javax.swing.JButton();
        jPasswordFieldContrasena = new javax.swing.JPasswordField();
        botonAceptar = new javax.swing.JButton();
        labelRegistro = new javax.swing.JLabel();
        BtnShowPass = new javax.swing.JButton();
        BtnShowPass1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Usuario:");

        jLabel2.setText("Contraseña:");

        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        jPasswordFieldContrasena.setEchoChar('\u2688');

        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        labelRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegistroMouseClicked(evt);
            }
        });

        BtnShowPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnShowPassActionPerformed(evt);
            }
        });

        BtnShowPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnShowPass1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldUsuario)
                    .addComponent(jPasswordFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnShowPass, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnShowPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnShowPass1))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jPasswordFieldContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnShowPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.jTextFieldUsuario.setText("");
        this.jPasswordFieldContrasena.setText("");
        this.jTextFieldUsuario.requestFocus();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void labelRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegistroMouseClicked
        try {
            this.setVisible(false);
            new RegistroView().setVisible(true);
        } catch (URISyntaxException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_labelRegistroMouseClicked

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed

        //recogo los valores de la ventana
        String user = this.jTextFieldUsuario.getText();
        char[] passwd = this.jPasswordFieldContrasena.getPassword();
        String password = new String(passwd); //convierto en cadena el password

        String sqlLogin = "SELECT * FROM usuario WHERE login=?";
        try (Connection conn = DriverManager.getConnection(urlDB, "root", "");) {
            PreparedStatement ps = conn.prepareStatement(sqlLogin);
            ps.setString(1, user);
            ResultSet rs = ps.executeQuery();

            //si no existe el usuario
            if (!rs.next()) {
                JOptionPane.showMessageDialog(null, "Este usuario no está registrado", "Usuario inexistente", JOptionPane.ERROR_MESSAGE);
                return;
            }

            //si existe el usuario
            Usuario usuario = new Usuario(
                    rs.getInt(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getInt(4)
            );

            int intentos = rs.getInt(5);

            if (usuario.getBlocked() == 1) {    //si el usuaio está bloqueado
                JOptionPane.showMessageDialog(null, "El usuario está actualmente bloqueado", "Bloqueado", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (usuario.getPassword().equals(password)) {
                resetIntentos(conn, user);
                JOptionPane.showMessageDialog(null, "Conectado", "Conectado", JOptionPane.INFORMATION_MESSAGE);
            } else {
                intentos++;
                if (intentos == 3) {
                    bloquearUsuario(conn, user, intentos);                   
                } else {
                    actualizarIntentos(conn, user, intentos);
                }
                JOptionPane.showMessageDialog(null, "La contraseña que has introducido no es correcta", "Contraseña erronea", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void BtnShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnShowPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnShowPassActionPerformed

    private void BtnShowPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnShowPass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnShowPass1ActionPerformed

    private void resetIntentos(Connection conn, String user) throws SQLException {
        String sql = "UPDATE usuario SET intentos=0 WHERE login=?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, user);
            ps.executeUpdate();
        }
    }

    private void actualizarIntentos(Connection conn, String user, int intentos) throws SQLException {
        String sql = "UPDATE usuario SET intentos=? WHERE login=?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, intentos);
            ps.setString(2, user);
            ps.executeUpdate();
        }

    }

    private void bloquearUsuario(Connection conn, String user, int intentos) throws SQLException {
        String sql = "UPDATE usuario SET blocked=1, intentos=? WHERE login=?";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, intentos);
            ps.setString(2, user);
            ps.executeUpdate();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnShowPass;
    private javax.swing.JButton BtnShowPass1;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordFieldContrasena;
    private javax.swing.JTextField jTextFieldUsuario;
    private javax.swing.JLabel labelRegistro;
    // End of variables declaration//GEN-END:variables
}
