/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import modelo.Contacto;

/**
 *
 * @author goncalda
 */
public class GuiAddContacto extends javax.swing.JFrame {

    private HashMap<String, Contacto> listaContactos;

    /**
     * Creates new form AgregarContacto
     */
    /*public GuiAddContacto(HashMap<String, Contacto> listaContactos) {
        this.listaContactos = listaContactos;
        initComponents();
        setFrame();
    }*/

    private void setFrame() {
        this.setLocationRelativeTo(null);
        this.LstNumTel.setModel(new DefaultListModel<>());
        this.setTitle("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CampoA = new javax.swing.JPanel();
        LblName = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        LblApp1 = new javax.swing.JLabel();
        TxtApp1 = new javax.swing.JTextField();
        LblApp2 = new javax.swing.JLabel();
        TxtApp2 = new javax.swing.JTextField();
        LblTel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        LstNumTel = new javax.swing.JList<>();
        Desc = new javax.swing.JPanel();
        ScrollDesc = new javax.swing.JScrollPane();
        ContDesc = new javax.swing.JTextArea();
        LblDesc = new javax.swing.JLabel();
        CampoB = new javax.swing.JPanel();
        LblMail = new javax.swing.JLabel();
        TxtMail = new javax.swing.JTextField();
        LblBirthDay = new javax.swing.JLabel();
        TxtBirthDay = new javax.swing.JTextField();
        ConfBtn = new javax.swing.JPanel();
        ContactAcept = new javax.swing.JButton();
        ContactCancel = new javax.swing.JButton();
        ContactClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(275, 355));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        LblName.setText("Nombre");

        TxtName.setMaximumSize(new java.awt.Dimension(155, 25));
        TxtName.setMinimumSize(new java.awt.Dimension(155, 25));
        TxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNameActionPerformed(evt);
            }
        });

        LblApp1.setText("Primer apellido");

        TxtApp1.setMaximumSize(new java.awt.Dimension(155, 25));
        TxtApp1.setMinimumSize(new java.awt.Dimension(155, 25));

        LblApp2.setText("Segundo apellido");

        TxtApp2.setMaximumSize(new java.awt.Dimension(155, 25));
        TxtApp2.setMinimumSize(new java.awt.Dimension(155, 25));

        LblTel.setText("Teléfonos");

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        LstNumTel.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        LstNumTel.setMaximumSize(new java.awt.Dimension(155, 25));
        LstNumTel.setMinimumSize(new java.awt.Dimension(155, 25));
        jScrollPane3.setViewportView(LstNumTel);

        javax.swing.GroupLayout CampoALayout = new javax.swing.GroupLayout(CampoA);
        CampoA.setLayout(CampoALayout);
        CampoALayout.setHorizontalGroup(
            CampoALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampoALayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(CampoALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblApp2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblApp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CampoALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(TxtApp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtApp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        CampoALayout.setVerticalGroup(
            CampoALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampoALayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(CampoALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CampoALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TxtApp1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblApp1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CampoALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(LblApp2)
                    .addComponent(TxtApp2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CampoALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTel))
                .addGap(0, 0, 0))
        );

        ContDesc.setColumns(20);
        ContDesc.setRows(5);
        ScrollDesc.setViewportView(ContDesc);

        LblDesc.setText("Descripcion");

        javax.swing.GroupLayout DescLayout = new javax.swing.GroupLayout(Desc);
        Desc.setLayout(DescLayout);
        DescLayout.setHorizontalGroup(
            DescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(DescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollDesc)
                    .addComponent(LblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        DescLayout.setVerticalGroup(
            DescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(LblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        LblMail.setText("Correo");

        TxtMail.setMaximumSize(new java.awt.Dimension(155, 25));
        TxtMail.setMinimumSize(new java.awt.Dimension(155, 25));

        LblBirthDay.setText("Cumpleaños");

        TxtBirthDay.setMaximumSize(new java.awt.Dimension(155, 25));
        TxtBirthDay.setMinimumSize(new java.awt.Dimension(155, 25));

        javax.swing.GroupLayout CampoBLayout = new javax.swing.GroupLayout(CampoB);
        CampoB.setLayout(CampoBLayout);
        CampoBLayout.setHorizontalGroup(
            CampoBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampoBLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(CampoBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CampoBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );
        CampoBLayout.setVerticalGroup(
            CampoBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CampoBLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(CampoBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TxtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblMail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CampoBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(TxtBirthDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblBirthDay))
                .addGap(0, 0, 0))
        );

        ConfBtn.setLayout(new java.awt.GridLayout(1, 0));

        ContactAcept.setText("Aceptar");
        ContactAcept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactAceptActionPerformed(evt);
            }
        });
        ConfBtn.add(ContactAcept);

        ContactCancel.setText("Cancelar");
        ContactCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactCancelActionPerformed(evt);
            }
        });
        ContactCancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContactCancelKeyPressed(evt);
            }
        });
        ConfBtn.add(ContactCancel);

        ContactClear.setText("Vaciar");
        ContactClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactClearActionPerformed(evt);
            }
        });
        ConfBtn.add(ContactClear);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CampoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CampoA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CampoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConfBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ContactCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_ContactCancelActionPerformed

    private void ContactCancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContactCancelKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_ContactCancelKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_formKeyPressed

    private void TxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNameActionPerformed

    private void ContactAceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactAceptActionPerformed
        // TODO add your handling code here:
        //recuperar la lista de contactos,

        

    }//GEN-LAST:event_ContactAceptActionPerformed

    private void ContactClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactClearActionPerformed
        // TODO add your handling code here:
        clearFields();

    }//GEN-LAST:event_ContactClearActionPerformed
    private void clearFields() {
        this.ContDesc.setText("");
        this.LstNumTel.removeAll();
        this.TxtMail.setText("");
        this.TxtName.setText("");
        this.TxtApp1.setText("");
        this.TxtApp2.setText("");
        System.out.println("vista.GuiAddContacto.clearFields()");
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GuiContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GuiContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GuiContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GuiContacto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GuiContacto().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CampoA;
    private javax.swing.JPanel CampoB;
    private javax.swing.JPanel ConfBtn;
    private javax.swing.JTextArea ContDesc;
    private javax.swing.JButton ContactAcept;
    private javax.swing.JButton ContactCancel;
    private javax.swing.JButton ContactClear;
    private javax.swing.JPanel Desc;
    private javax.swing.JLabel LblApp1;
    private javax.swing.JLabel LblApp2;
    private javax.swing.JLabel LblBirthDay;
    private javax.swing.JLabel LblDesc;
    private javax.swing.JLabel LblMail;
    private javax.swing.JLabel LblName;
    private javax.swing.JLabel LblTel;
    private javax.swing.JList<String> LstNumTel;
    private javax.swing.JScrollPane ScrollDesc;
    private javax.swing.JTextField TxtApp1;
    private javax.swing.JTextField TxtApp2;
    private javax.swing.JTextField TxtBirthDay;
    private javax.swing.JTextField TxtMail;
    private javax.swing.JTextField TxtName;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
