/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gonzalezdanielretocolas;

import java.time.LocalDateTime;
import javax.swing.JFrame;
import java.util.LinkedList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author goncalda
 */
public class NavegadorSwing extends javax.swing.JFrame {

    private LinkedList<WebPage> historial;
    private DefaultListModel<WebPage> modeloListaHistorial;

    /**
     * Creates new form NavegadorSwing
     */
    public NavegadorSwing() {
        initComponents();
        setFrame();
    }

    private void setFrame() {
        this.setTitle("Simulador historial de busqueda");
        historial = new LinkedList<>();
        modeloListaHistorial = new DefaultListModel<>();
        this.ListHISTORIAL.setModel(modeloListaHistorial);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setTitle("Navegador Swing 1ºDAM");
        this.TextFieldTITULO.setFocusable(false);
        this.TextFieldTITULO.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Navegacion = new javax.swing.JPanel();
        ButtonATRAS = new javax.swing.JButton();
        ButtonVISITAR = new javax.swing.JButton();
        LabelURL = new javax.swing.JLabel();
        TextFieldURL = new javax.swing.JTextField();
        LabelTITULO = new javax.swing.JLabel();
        TextFieldTITULO = new javax.swing.JTextField();
        Info = new javax.swing.JPanel();
        LabelINFO = new javax.swing.JLabel();
        Historial = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListHISTORIAL = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Navegacion.setLayout(new javax.swing.BoxLayout(Navegacion, javax.swing.BoxLayout.LINE_AXIS));

        ButtonATRAS.setText("Atras");
        ButtonATRAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonATRASActionPerformed(evt);
            }
        });
        Navegacion.add(ButtonATRAS);

        ButtonVISITAR.setText("Visitar");
        ButtonVISITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVISITARActionPerformed(evt);
            }
        });
        Navegacion.add(ButtonVISITAR);

        LabelURL.setText("URL: ");
        Navegacion.add(LabelURL);

        TextFieldURL.setColumns(25);
        Navegacion.add(TextFieldURL);

        LabelTITULO.setText("Título: ");
        Navegacion.add(LabelTITULO);

        TextFieldTITULO.setColumns(10);
        Navegacion.add(TextFieldTITULO);

        getContentPane().add(Navegacion, java.awt.BorderLayout.PAGE_START);

        Info.setLayout(new javax.swing.BoxLayout(Info, javax.swing.BoxLayout.LINE_AXIS));

        LabelINFO.setText("Página actual: ");
        Info.add(LabelINFO);

        getContentPane().add(Info, java.awt.BorderLayout.PAGE_END);

        Historial.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(ListHISTORIAL);

        Historial.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(Historial, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVISITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVISITARActionPerformed
        // TODO add your handling code here:
        visitarPagina();
        
    }//GEN-LAST:event_ButtonVISITARActionPerformed

    private void ButtonATRASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonATRASActionPerformed
        // TODO add your handling code here:
        
        String urlWebAnterior = this.ListHISTORIAL.
        visitarPagina(urlWebAnterior);
    }//GEN-LAST:event_ButtonATRASActionPerformed
    private void visitarPagina() {
    String url = this.TextFieldURL.getText(), titulo;
        if (url.isBlank() || url == null) {
            JOptionPane.showMessageDialog(this, "Debes introducir una url", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            Pattern regexWPG = Pattern.compile("^www\\.([A-Za-z0-9-]+)\\.[A-Za-z]{1,3}$");
            Matcher m = null;

            m = regexWPG.matcher(url);
            if (!m.matches()) {
                String msgErrorFormato ="Formato de url inválido\n"
                        + "Debe seguir el formato:\n"
                        + " 'www.tupagina.dom'\n"
                        + "Donde el dominio tiene entre una y tres letras";
                JOptionPane.showMessageDialog(this,msgErrorFormato , "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                titulo = m.group(1);
                this.TextFieldTITULO.setText(titulo);
                WebPage paginaBuscada = new WebPage(url, titulo, LocalDateTime.now());
                modeloListaHistorial.add(0,paginaBuscada);
                this.LabelINFO.setText("Página actual: "+url);
                this.ListHISTORIAL.setSelectedIndex(0);
            }

        }
    
    
    }
    private void visitarPagina(String url) {
        String titulo;
        if (url.isBlank() || url == null) {
            JOptionPane.showMessageDialog(this, "Debes introducir una url", "Error", JOptionPane.ERROR_MESSAGE);

        } else {
            Pattern regexWPG = Pattern.compile("^www\\.([A-Za-z0-9-]+)\\.[A-Za-z]{1,3}$");
            Matcher m = null;

            m = regexWPG.matcher(url);
            if (!m.matches()) {
                String msgErrorFormato ="Formato de url inválido\n"
                        + "Debe seguir el formato:\n"
                        + " 'www.tupagina.dom'\n"
                        + "Donde el dominio tiene entre una y tres letras";
                JOptionPane.showMessageDialog(this,msgErrorFormato , "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                titulo = m.group(1);
                this.TextFieldTITULO.setText(titulo);
                WebPage paginaBuscada = new WebPage(url, titulo, LocalDateTime.now());
                modeloListaHistorial.add(0,paginaBuscada);
                this.LabelINFO.setText("Página actual: "+url);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NavegadorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NavegadorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NavegadorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NavegadorSwing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NavegadorSwing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonATRAS;
    private javax.swing.JButton ButtonVISITAR;
    private javax.swing.JPanel Historial;
    private javax.swing.JPanel Info;
    private javax.swing.JLabel LabelINFO;
    private javax.swing.JLabel LabelTITULO;
    private javax.swing.JLabel LabelURL;
    private javax.swing.JList<WebPage> ListHISTORIAL;
    private javax.swing.JPanel Navegacion;
    private javax.swing.JTextField TextFieldTITULO;
    private javax.swing.JTextField TextFieldURL;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
