/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Encuesta;

/**
 *
 * @author goncalda
 */
public class VistaEncuesta extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public VistaEncuesta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBtnVotar = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jRadioButtonYes = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        jRadioButtonMaybe = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        BotLat = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setLayout(new java.awt.GridLayout(0, 3, 10, 0));

        GrupoBtnVotar.add(jRadioButtonYes);
        jRadioButtonYes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButtonYes.setText("Si");
        jRadioButtonYes.setAutoscrolls(true);
        jRadioButtonYes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jRadioButtonYes);

        GrupoBtnVotar.add(jRadioButtonNo);
        jRadioButtonNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButtonNo.setText("No");
        jRadioButtonNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jRadioButtonNo);

        GrupoBtnVotar.add(jRadioButtonMaybe);
        jRadioButtonMaybe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jRadioButtonMaybe.setText("Puede");
        jRadioButtonMaybe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jRadioButtonMaybe);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("¿España va a ganar el mundial?");
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        BotLat.setLayout(new java.awt.GridLayout(0, 1));

        jButton1.setText("Confirmar");
        BotLat.add(jButton1);

        jButton2.setText("Borrrar");
        BotLat.add(jButton2);

        getContentPane().add(BotLat, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaEncuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotLat;
    private javax.swing.ButtonGroup GrupoBtnVotar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonMaybe;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonYes;
    // End of variables declaration//GEN-END:variables
}
