/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicios.Moto;

import javax.swing.JOptionPane;

/**
 *
 * @author goncalda
 */
public class GUI_App_Moto extends javax.swing.JFrame {

    /**
     * Creates new form GUI_App_Moto
     */
    public GUI_App_Moto(MotoCorregida moto) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        String titleString=new String();
        titleString+=moto.getMarca()+moto.getMatricula()+moto.getModelo();
        setTitle(titleString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SalpicaderoPrincipal = new javax.swing.JPanel();
        OcupacionActual = new javax.swing.JLabel();
        LabelPasajeros = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LabelCombustible = new javax.swing.JLabel();
        LabelVelocidad = new javax.swing.JLabel();
        VelocidadActual = new javax.swing.JLabel();
        Botonera = new javax.swing.JPanel();
        Ignicion = new javax.swing.JToggleButton();
        Bajar = new javax.swing.JButton();
        Subir = new javax.swing.JButton();
        Decelerar = new javax.swing.JButton();
        Acelerar = new javax.swing.JButton();
        Repostar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SalpicaderoPrincipal.setBackground(new java.awt.Color(3, 30, 3));

        OcupacionActual.setText("jLabel5");

        LabelPasajeros.setText("Pasajeros");

        jLabel6.setText("jLabel6");

        LabelCombustible.setText("Combustible");

        LabelVelocidad.setText("Velocidad");

        VelocidadActual.setText("jLabel4");

        javax.swing.GroupLayout SalpicaderoPrincipalLayout = new javax.swing.GroupLayout(SalpicaderoPrincipal);
        SalpicaderoPrincipal.setLayout(SalpicaderoPrincipalLayout);
        SalpicaderoPrincipalLayout.setHorizontalGroup(
            SalpicaderoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalpicaderoPrincipalLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(SalpicaderoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OcupacionActual)
                    .addComponent(LabelPasajeros))
                .addGap(45, 45, 45)
                .addGroup(SalpicaderoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelCombustible)
                    .addComponent(jLabel6))
                .addGap(45, 45, 45)
                .addGroup(SalpicaderoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VelocidadActual)
                    .addComponent(LabelVelocidad))
                .addGap(5, 5, 5))
        );
        SalpicaderoPrincipalLayout.setVerticalGroup(
            SalpicaderoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalpicaderoPrincipalLayout.createSequentialGroup()
                .addGroup(SalpicaderoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SalpicaderoPrincipalLayout.createSequentialGroup()
                        .addGroup(SalpicaderoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelPasajeros)
                            .addComponent(LabelCombustible))
                        .addGap(18, 18, 18)
                        .addGroup(SalpicaderoPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OcupacionActual)
                            .addComponent(jLabel6)))
                    .addGroup(SalpicaderoPrincipalLayout.createSequentialGroup()
                        .addComponent(LabelVelocidad)
                        .addGap(18, 18, 18)
                        .addComponent(VelocidadActual)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Ignicion.setText("Arrancar");
        Ignicion.setMaximumSize(new java.awt.Dimension(64, 64));
        Ignicion.setMinimumSize(new java.awt.Dimension(32, 32));
        Ignicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgnicionActionPerformed(evt);
            }
        });

        Bajar.setText("Bajar");

        Subir.setText("Subir");

        Decelerar.setText("Frenar");

        Acelerar.setText("Acelerar");

        Repostar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejercicios/Moto/Assets/FuelIcon.png"))); // NOI18N
        Repostar.setText("Repostar");
        Repostar.setMaximumSize(new java.awt.Dimension(64, 64));
        Repostar.setMinimumSize(new java.awt.Dimension(64, 64));
        Repostar.setPreferredSize(new java.awt.Dimension(64, 64));
        Repostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepostarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotoneraLayout = new javax.swing.GroupLayout(Botonera);
        Botonera.setLayout(BotoneraLayout);
        BotoneraLayout.setHorizontalGroup(
            BotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotoneraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Bajar)
                    .addComponent(Subir)
                    .addComponent(Ignicion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(Decelerar)
                        .addComponent(Acelerar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotoneraLayout.createSequentialGroup()
                        .addComponent(Repostar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        BotoneraLayout.setVerticalGroup(
            BotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotoneraLayout.createSequentialGroup()
                .addGroup(BotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ignicion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Repostar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Decelerar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Bajar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BotoneraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Acelerar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Subir, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(SalpicaderoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(SalpicaderoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Botonera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(594, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IgnicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgnicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IgnicionActionPerformed

    private void RepostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepostarActionPerformed
        // TODO add your handling code here:
        double combustibleRepostado;
        do {
            combustibleRepostado  = Double.parseDouble(JOptionPane.showInputDialog(this, "Introduce el combustible a repostar", 0));
        } while(combustibleRepostado<=0);
        
        System.out.printf("Repostando %f",combustibleRepostado);
    }//GEN-LAST:event_RepostarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_App_Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_App_Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_App_Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_App_Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_App_Moto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acelerar;
    private javax.swing.JButton Bajar;
    private javax.swing.JPanel Botonera;
    private javax.swing.JButton Decelerar;
    private javax.swing.JToggleButton Ignicion;
    private javax.swing.JLabel LabelCombustible;
    private javax.swing.JLabel LabelPasajeros;
    private javax.swing.JLabel LabelVelocidad;
    private javax.swing.JLabel OcupacionActual;
    private javax.swing.JButton Repostar;
    private javax.swing.JPanel SalpicaderoPrincipal;
    private javax.swing.JButton Subir;
    private javax.swing.JLabel VelocidadActual;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
