/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gf.local;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author goncalda
 */
public class GUIEjemplo extends javax.swing.JFrame {

    public static final String url = "jdbc:mysql://localhost:3306/ejemplo";
    public Connection con;

    /**
     * Creates new form GUIEjemplo
     */
    public GUIEjemplo() {
        initComponents();
        conTest();
        setFrame();
    }

    private void setFrame() {
        this.setTitle("Ejemplo JDBC - BD:ejemplo");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    private void conTest() {
        try {
            //Abrir conexion
            this.con = DriverManager.getConnection(url, "root", "");

            //Mandar consultas + procesar resultado
            /**
             * Mandar una select
             */
            String select = "select * from tabla1";
            Statement st = con.createStatement();
            st.executeQuery(select);
            
            //Cerrar recursos
        } catch (SQLException ex) {
            System.err.println("Error al conectar: " + ex.getLocalizedMessage());
            JOptionPane.showMessageDialog(this, "ERROR: " + ex.getLocalizedMessage(), "no se ha podido conectar a: " + url, 0);
        } finally {
            try {
                this.con.close();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
        System.out.println("Conexion realizada");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenBD = new javax.swing.JMenu();
        Select = new javax.swing.JMenuItem();
        Insert = new javax.swing.JMenuItem();
        Update = new javax.swing.JMenuItem();
        Delete = new javax.swing.JMenuItem();
        MenAplicacion = new javax.swing.JMenu();
        Quit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setFocusTraversalPolicyProvider(true);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        MenBD.setText("BD");

        Select.setText("Select");
        Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectActionPerformed(evt);
            }
        });
        MenBD.add(Select);

        Insert.setText("Insert");
        MenBD.add(Insert);

        Update.setText("Update");
        MenBD.add(Update);

        Delete.setText("Delete");
        MenBD.add(Delete);

        jMenuBar1.add(MenBD);

        MenAplicacion.setText("Aplicacion");

        Quit.setText("Quit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });
        MenAplicacion.add(Quit);

        jMenuBar1.add(MenAplicacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_QuitActionPerformed

    private void SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectActionPerformed

        // TODO add your handling code here:
        try {
            //Abrir conexion
            this.con = DriverManager.getConnection(url, "root", "");

            //Mandar consultas + procesar resultado
            String select = "select * from tabla1";
            Statement consulta = con.createStatement();
            ResultSet resultados = consulta.executeQuery(select);
            StringBuilder stb = new StringBuilder();
            while (resultados.next()) {
                //resultados.next();
                stb.append(resultados.getInt(1));
                stb.append('\t');

                stb.append(resultados.getString(2));
                stb.append('\t');

                stb.append(resultados.getDouble(3));
                stb.append('\n');
            }
            this.jTextArea1.setText(stb.toString());
            System.out.println(stb);
            //Cerrar recursos
        } catch (SQLException ex) {
            System.err.println("Error al conectar: " + ex.getLocalizedMessage());
            JOptionPane.showMessageDialog(this, "ERROR: " + ex.getLocalizedMessage(), "no se ha podido conectar a: " + url, 0);
        } finally {
            try {
                this.con.close();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_SelectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEjemplo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEjemplo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Delete;
    private javax.swing.JMenuItem Insert;
    private javax.swing.JMenu MenAplicacion;
    private javax.swing.JMenu MenBD;
    private javax.swing.JMenuItem Quit;
    private javax.swing.JMenuItem Select;
    private javax.swing.JMenuItem Update;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
