/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import modelo.Contacto;

/**
 *
 * @author goncalda
 */
public class GUIAgendaContactos extends javax.swing.JFrame {

    private DefaultListModel<Contacto> modListaContacto;
    private HashMap<Integer, Contacto> listaContactos;
    private GuiContacto guiAddContact;
    private GuiFiltrarContacto guiFilterContact;

    /**
     * Creates new form GUIAgendaContactos
     */
    public GUIAgendaContactos(GuiContacto guiAñadirContacto, GuiFiltrarContacto guiFiltrarContacto, HashMap<Integer, Contacto> listaContactos) {
        this.listaContactos = listaContactos;
        initComponents();
        setFrame();
        this.guiFilterContact = guiFiltrarContacto;
        this.guiAddContact = guiAñadirContacto;
    }

    private void setFrame() {
        this.setLocationRelativeTo(null);
        this.setTitle("Agenda de contactos");

        modListaContacto = new DefaultListModel<>();
        this.jList1.setModel(modListaContacto);
        /* Set the Nimbus look and feel */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        OptContacto = new javax.swing.JMenu();
        Añadir = new javax.swing.JMenuItem();
        Buscar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        Borrar = new javax.swing.JMenuItem();
        OptAgenda = new javax.swing.JMenu();
        Listar = new javax.swing.JMenuItem();
        Vaciar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_END);

        OptContacto.setText("Contacto");

        Añadir.setText("Añadir");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });
        OptContacto.add(Añadir);

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        OptContacto.add(Buscar);

        Modificar.setText("Modificar");
        OptContacto.add(Modificar);

        Borrar.setText("Borrar");
        OptContacto.add(Borrar);

        jMenuBar1.add(OptContacto);

        OptAgenda.setText("Agenda");

        Listar.setText("Listar");
        OptAgenda.add(Listar);

        Vaciar.setText("Vaciar");
        OptAgenda.add(Vaciar);

        jMenuBar1.add(OptAgenda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
        // TODO add your handling code here:
        guiAddContact.setTitle("Nuevo contacto");
        guiAddContact.setVisible(true);
    }//GEN-LAST:event_AñadirActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        GuiFiltrarContacto guiFiltrarContacto = new GuiFiltrarContacto(listaContactos);
        guiFiltrarContacto.setVisible(true);
    }//GEN-LAST:event_BuscarActionPerformed

    public void setModListaContacto(DefaultListModel<Contacto> modListaContacto) {
        this.modListaContacto = modListaContacto;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Añadir;
    private javax.swing.JMenuItem Borrar;
    private javax.swing.JMenuItem Buscar;
    private javax.swing.JMenuItem Listar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JMenu OptAgenda;
    private javax.swing.JMenu OptContacto;
    private javax.swing.JMenuItem Vaciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Contacto> jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
