/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Contacto;

/**
 *
 * @author goncalda
 */
public class GUIAgendaContactos extends javax.swing.JFrame {

    private DefaultListModel<Contacto> modListaContacto;
    private HashMap<Integer, Contacto> listaContactos;
    private final GuiAñadirContacto guiAddContact;
    private final GuiFiltrarContacto guiFilterContact;
    private final GUIListarContactos guiListarContactos;

    /**
     * Creates new form GUIAgendaContactos
     */
    public GUIAgendaContactos(HashMap<Integer, Contacto> listaContactos) {
        this.listaContactos = listaContactos;
        initComponents();
        setFrame();
        this.guiFilterContact = new GuiFiltrarContacto(listaContactos, this);
        this.guiAddContact = new GuiAñadirContacto(listaContactos, this);
        this.guiListarContactos = new GUIListarContactos(listaContactos, this);
    }

    private void setFrame() {
        this.setLocationRelativeTo(null);
        this.setTitle("Agenda de contactos");

        modListaContacto = new DefaultListModel<>();
        this.JlistContactos.setModel(modListaContacto);
        /* Set the Nimbus look and feel */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JlistContactos = new javax.swing.JList<>();
        LabelIdContacto = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        OptContacto = new javax.swing.JMenu();
        Añadir = new javax.swing.JMenuItem();
        Buscar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        Borrar = new javax.swing.JMenuItem();
        OptAgenda = new javax.swing.JMenu();
        Listar = new javax.swing.JMenuItem();
        Vaciar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));

        JlistContactos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        JlistContactos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                JlistContactosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(JlistContactos);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
        getContentPane().add(LabelIdContacto, java.awt.BorderLayout.PAGE_END);

        OptContacto.setText("Contacto");

        Añadir.setText("Añadir");
        Añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirActionPerformed(evt);
            }
        });
        OptContacto.add(Añadir);

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        OptContacto.add(Buscar);

        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        OptContacto.add(Modificar);

        Borrar.setText("Borrar");
        Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarActionPerformed(evt);
            }
        });
        OptContacto.add(Borrar);

        jMenuBar1.add(OptContacto);

        OptAgenda.setText("Agenda");

        Listar.setText("Listar");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });
        OptAgenda.add(Listar);

        Vaciar.setText("Vaciar");
        Vaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaciarActionPerformed(evt);
            }
        });
        OptAgenda.add(Vaciar);

        jMenuBar1.add(OptAgenda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirActionPerformed
        // TODO add your handling code here:
        guiAddContact.setTitle("Nuevo contacto");
        guiAddContact.clearFields();
        guiAddContact.setVisible(true);

    }//GEN-LAST:event_AñadirActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        this.guiFilterContact.clearFields();
        guiFilterContact.setTitle("Buscar contacto");
        guiFilterContact.setVisible(true);

    }//GEN-LAST:event_BuscarActionPerformed

    private void VaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaciarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Vaciar lista de contactos", "Confirmacion", JOptionPane.YES_NO_OPTION) == 1) {
            System.out.println("No");
        } else {
            this.listaContactos.clear();
            updateListaContacto(listaContactos);
        }
    }//GEN-LAST:event_VaciarActionPerformed

    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
        // TODO add your handling code here:
        updateListaContacto(listaContactos);
        guiListarContactos.setVisible(true);
    }//GEN-LAST:event_ListarActionPerformed

    private void JlistContactosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_JlistContactosValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
            Contacto selectContacto = JlistContactos.getSelectedValue();
            if (selectContacto != null) {
                System.out.println(selectContacto);
                this.LabelIdContacto.setText("  ID Contacto: "
                        + selectContacto.hashCode()
                );
            }
        }
    }//GEN-LAST:event_JlistContactosValueChanged

    private void BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarActionPerformed
        // TODO add your handling code here:
        Contacto contactoParaEliminar = JlistContactos.getSelectedValue();
        if (contactoParaEliminar == null) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un contacto para eliminarlo", "ERROR", 0);
            this.Buscar.doClick();
        } else {
            if (listaContactos.remove(contactoParaEliminar.hashCode(), contactoParaEliminar)) {
                JOptionPane.showMessageDialog(this, "Contacto eliminado con éxito", "Informacion", 1);
                updateListaContacto(listaContactos);
            } else {
                JOptionPane.showMessageDialog(this, "Error no se ha encontrado un contacto para eliminarlo", "ERROR", 0);
            }
        }


    }//GEN-LAST:event_BorrarActionPerformed

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed
        // TODO add your handling code here:
        Contacto contactoParaModificar = JlistContactos.getSelectedValue();
        if (contactoParaModificar == null) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un contacto para modificarlo", "ERROR", 0);
            this.Buscar.doClick();
        } else {
            if (!listaContactos.remove(contactoParaModificar.hashCode(), contactoParaModificar)) {
                JOptionPane.showMessageDialog(this, "Error no se ha encontrado un contacto para eliminarlo", "ERROR", 0);
            } else {
                JOptionPane.showMessageDialog(this, "Contacto eliminado con éxito", "Informacion", 1);
                Contacto cModificado = contactoParaModificar.clone();
                this.guiAddContact.setVisible(true);
                
            }
        }
    }//GEN-LAST:event_ModificarActionPerformed

    public void updateListaContacto(HashMap<Integer, Contacto> listaContactos) {
        this.modListaContacto = new DefaultListModel<>();
        for (Contacto contacto : listaContactos.values()) {
            this.modListaContacto.addElement(contacto);
        }
        this.JlistContactos.setModel(modListaContacto);
    }

    public void updateListaContacto(HashSet<Contacto> listaContactos) {
        this.modListaContacto = new DefaultListModel<>();
        for (Contacto contacto : listaContactos) {
            this.modListaContacto.addElement(contacto);
        }
        this.JlistContactos.setModel(modListaContacto);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Añadir;
    private javax.swing.JMenuItem Borrar;
    private javax.swing.JMenuItem Buscar;
    private javax.swing.JList<Contacto> JlistContactos;
    private javax.swing.JLabel LabelIdContacto;
    private javax.swing.JMenuItem Listar;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JMenu OptAgenda;
    private javax.swing.JMenu OptContacto;
    private javax.swing.JMenuItem Vaciar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
