/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.formdev.flatlaf.FlatDarkLaf;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedHashMap;
import modelo.Contacto;

/**
 *
 * @author goncalda
 */
public class GuiOrdenarContactos extends javax.swing.JFrame {

    private Comparator<Contacto> compContactos;
    private LinkedHashMap<Integer, Contacto> listaContactos;
    private final GuiPrincipalAgendaContactos guiPadre;

    /**
     * Creates new form GUIListarContactos
     *
     * @param listaContactos
     * @param guiPadre
     */
    public GuiOrdenarContactos(LinkedHashMap<Integer, Contacto> listaContactos, GuiPrincipalAgendaContactos guiPadre) {
        FlatDarkLaf.setup();
        this.guiPadre = guiPadre;
        this.listaContactos = listaContactos;
        compContactos = Comparator.comparing((Contacto c) -> 0);
        initComponents();
        setFrame();
    }

    private void setFrame() {
        setLocationRelativeTo(null);
        setTitle("Ordenar contactos");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base = new javax.swing.JPanel();
        ContSelectores = new javax.swing.JPanel();
        LblAlfabeto = new javax.swing.JLabel();
        AlfabetoTipoOrden = new javax.swing.JComboBox<>();
        ActivadorAlfabetico = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        FechaTipoOrdenar = new javax.swing.JComboBox<>();
        ActivadorFechaAdicion = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LblAlfabeto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LblAlfabeto.setText("Alfabéticamente");

        AlfabetoTipoOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendente", "Descendente" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Fecha");

        FechaTipoOrdenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendente", "Descendente" }));
        FechaTipoOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechaTipoOrdenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContSelectoresLayout = new javax.swing.GroupLayout(ContSelectores);
        ContSelectores.setLayout(ContSelectoresLayout);
        ContSelectoresLayout.setHorizontalGroup(
            ContSelectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContSelectoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContSelectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblAlfabeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContSelectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FechaTipoOrdenar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AlfabetoTipoOrden, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContSelectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ActivadorFechaAdicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActivadorAlfabetico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ContSelectoresLayout.setVerticalGroup(
            ContSelectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContSelectoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContSelectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(ContSelectoresLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(ContSelectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FechaTipoOrdenar)
                            .addComponent(ActivadorFechaAdicion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContSelectoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(ContSelectoresLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(AlfabetoTipoOrden))
                    .addComponent(LblAlfabeto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ContSelectoresLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(ActivadorAlfabetico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jButton1.setText("Ordenar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        javax.swing.GroupLayout BaseLayout = new javax.swing.GroupLayout(Base);
        Base.setLayout(BaseLayout);
        BaseLayout.setHorizontalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaseLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(BaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContSelectores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BaseLayout.setVerticalGroup(
            BaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ContSelectores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<Contacto> contactosOrdenados = new ArrayList<>(listaContactos.values());
        if (this.ActivadorAlfabetico.isSelected()) {
            System.out.println("Listar alfabetico");
            System.out.println(this.AlfabetoTipoOrden.getSelectedIndex());

            Collections.sort(contactosOrdenados, compContactos
                    .thenComparing(Contacto::getNombre)
                    .thenComparing(Contacto::getApellido1)
                    .thenComparing(Contacto::getApellido2)
            );
            if (this.AlfabetoTipoOrden.getSelectedIndex() == 1) {
                Collections.reverse(contactosOrdenados);
                System.out.println("Reversed");
            }
            System.out.println("Alfabetico");
            guiPadre.updateListaContacto(contactosOrdenados);

        }

        if (this.ActivadorFechaAdicion.isSelected()) {
            System.out.println("Listar fecha");
            System.out.println(this.FechaTipoOrdenar.getSelectedIndex());

            Collections.sort(contactosOrdenados, compContactos
                    .thenComparing(Contacto::getFechaAñadido)
            );
            if (this.FechaTipoOrdenar.getSelectedIndex() == 1) {
                Collections.reverse(contactosOrdenados);
                System.out.println("Reversed");
            }
            System.out.println("Por fechas");
            guiPadre.updateListaContacto(contactosOrdenados);

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void FechaTipoOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechaTipoOrdenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechaTipoOrdenarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ActivadorAlfabetico;
    private javax.swing.JCheckBox ActivadorFechaAdicion;
    private javax.swing.JComboBox<String> AlfabetoTipoOrden;
    private javax.swing.JPanel Base;
    private javax.swing.JPanel ContSelectores;
    private javax.swing.JComboBox<String> FechaTipoOrdenar;
    private javax.swing.JLabel LblAlfabeto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
