/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SistemaPagos;
import SistemaPagos.MetodoPago;
import SistemaPagos.Bizum;
import SistemaPagos.Tarjeta;
import SistemaPagos.Paypal;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author goncalda
 */
public class InterfazPago extends javax.swing.JFrame {

    private boolean importeCorrecto;

    /**
     * Creates new form InterfazPago
     */
    public InterfazPago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLocationRelativeTo(null);
        setTitle("Esa: SPDP");
        SelectorImporte = new javax.swing.JTextField();
        TituloImporte = new javax.swing.JLabel();
        ImporteAleatorio = new javax.swing.JButton();
        SelectorMetodo = new javax.swing.JComboBox<>();
        Justificante = new javax.swing.JTextArea();
        BotonConfirmPag = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        SelectorImporte.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                SelectorImporteFocusLost(evt);
            }
        });
        SelectorImporte.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }

            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                SelectorImporteInputMethodTextChanged(evt);
            }
        });
        SelectorImporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectorImporteActionPerformed(evt);
            }
        });

        TituloImporte.setText("Introduce el importe:");

        ImporteAleatorio.setText("Importe aleatorio");
        ImporteAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImporteAleatorioActionPerformed(evt);
            }
        });

        SelectorMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bizum", "Paypal", "Tarjeta" }));
        SelectorMetodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                SelectorMetodoItemStateChanged(evt);
            }
        });
        SelectorMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectorMetodoActionPerformed(evt);
            }
        });

        Justificante.setColumns(20);
        Justificante.setRows(5);

        BotonConfirmPag.setText("Pagar");
        BotonConfirmPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConfirmPagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Justificante, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(TituloImporte)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(SelectorImporte,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 148,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        false)
                                                                        .addComponent(BotonConfirmPag,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                        .addComponent(ImporteAleatorio,
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(SelectorMetodo,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 140,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(TituloImporte)
                                                .addComponent(SelectorImporte, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(SelectorMetodo,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ImporteAleatorio,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonConfirmPag, javax.swing.GroupLayout.DEFAULT_SIZE, 32,
                                        Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(Justificante, javax.swing.GroupLayout.PREFERRED_SIZE, 163,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectorImporteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SelectorImporteActionPerformed
        

    }// GEN-LAST:event_SelectorImporteActionPerformed

    private void ImporteAleatorioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ImporteAleatorioActionPerformed

        
        genImporteAleatorio();
    }// GEN-LAST:event_ImporteAleatorioActionPerformed

    private void SelectorMetodoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_SelectorMetodoActionPerformed
    }// GEN-LAST:event_SelectorMetodoActionPerformed

    private void SelectorMetodoItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_SelectorMetodoItemStateChanged

    }// GEN-LAST:event_SelectorMetodoItemStateChanged

    private void SelectorImporteFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_SelectorImporteFocusLost

    }// GEN-LAST:event_SelectorImporteFocusLost

    private void SelectorImporteInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {// GEN-FIRST:event_SelectorImporteInputMethodTextChanged

    }// GEN-LAST:event_SelectorImporteInputMethodTextChanged

    private void BotonConfirmPagActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BotonConfirmPagActionPerformed
        Justificante.setText("");
        importeCorrecto = true;
        double impSeleccionado;
        if (!SelectorImporte.getText().matches("^\\d+(?:[.,]\\d{1,2})?$")) {
            JOptionPane.showMessageDialog(this,
                    "El numero que debes introducir debe ser positivo hasta 2 decimales y denotados por . ó ,",
                    "Error dato inválido", JOptionPane.ERROR_MESSAGE);
            importeCorrecto = false;
        } else {
            impSeleccionado = Double.parseDouble(SelectorImporte.getText().trim().replace(",", "."));
            String optPago = (String) SelectorMetodo.getSelectedItem();
            SelectorImporte.setText("");
            Justificante.setText("Procesando pago...");
            switch (optPago) {
                case "Paypal" -> {
                    String correo;
                    boolean correoCorrecto;
                    do {
                        correoCorrecto = true;
                        correo = JOptionPane.showInputDialog(this, "Introduce tu correo de paypal",
                                "Solicitud datos de pago", JOptionPane.INFORMATION_MESSAGE);

                        try {
                            if (correo.isBlank())
                                throw new Exception();
                            correoCorrecto = correo.matches("^[A-Za-z0-9]+@[A-Za-z0-9]+\\.[a-z]+$");

                        } catch (Exception e) {
                            Justificante.setText("Cancelando operacion...");
                        }

                    } while (!correoCorrecto);
                    if (!correo.isBlank()) {
                        MetodoPago metodoPago = new Paypal(correo);
                        metodoPago.pagar(impSeleccionado);
                        System.out.println(metodoPago.obtenerComprobante());
                        Justificante.append(metodoPago.obtenerComprobante());
                    }

                }
                case "Bizum" -> {
                    String strNumTel;
                    boolean numTelCorrecto;
                    do {
                        numTelCorrecto = true;
                        strNumTel = JOptionPane.showInputDialog(this, "Introduce tu numero de telefono de bizum",
                                "Solicitud datos de pago", JOptionPane.INFORMATION_MESSAGE);
                        try {
                            if (strNumTel.isBlank())
                                throw new Exception();
                            numTelCorrecto = strNumTel.matches("^[1-9]{1}[0-9]{8}$");
                        } catch (Exception e) {
                            Justificante.setText("Cancelando operacion...");
                        }
                    } while (!numTelCorrecto);
                    if (!strNumTel.isBlank()) {
                        MetodoPago metodoPago = new Bizum(strNumTel);
                        metodoPago.pagar(impSeleccionado);
                        System.out.println(metodoPago.obtenerComprobante());
                        Justificante.append(metodoPago.obtenerComprobante());
                    }
                }
                case "Tarjeta" -> {
                    String strNumTar;
                    boolean numTarjCorrecto;
                    do {
                        numTarjCorrecto = true;
                        strNumTar = JOptionPane.showInputDialog(this, "Introduce tu numero de tarjeta bancaria",
                                "Solicitud datos de pago", JOptionPane.INFORMATION_MESSAGE);
                        try {
                            if (strNumTar.isBlank())
                                throw new Exception();
                            numTarjCorrecto = strNumTar.matches("^[1-9]{1}[0-9]{15}$");
                        } catch (Exception e) {
                            Justificante.setText("Cancelando operacion...");
                        }
                    } while (!numTarjCorrecto);
                    if (!strNumTar.isBlank()) {
                        MetodoPago metodoPago = new Tarjeta(strNumTar);
                        metodoPago.pagar(impSeleccionado);
                        System.out.println(metodoPago.obtenerComprobante());
                        Justificante.append(metodoPago.obtenerComprobante());
                    }
                }
                default -> {
                }
            }

        } 

    }// GEN-LAST:event_BotonConfirmPagActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazPago.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazPago.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazPago.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPago.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazPago().setVisible(true);
            }
        });
    }

    private void genImporteAleatorio() {
        Random rd = new Random();
        double impAleatorio = rd.nextDouble(0.1, 401);
        SelectorImporte.setText(String.format("%.2f", impAleatorio));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConfirmPag;
    private javax.swing.JButton ImporteAleatorio;
    private javax.swing.JTextArea Justificante;
    private javax.swing.JTextField SelectorImporte;
    private javax.swing.JComboBox<String> SelectorMetodo;
    private javax.swing.JLabel TituloImporte;
    // End of variables declaration//GEN-END:variables

}
