/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Encuesta.Vista;

import Encuesta.Modelo.Respuesta;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.ArrayList;

import javax.swing.JOptionPane;

/**
 *
 * @author goncalda
 */
public class GUIEncuesta extends javax.swing.JFrame {

    private ArrayList<Respuesta> listaVotaciones;
    private int favorables = 0, contrarios = 0, numVotos = 0;

    /**
     * Creates new form GUIEncuesta
     */
    public GUIEncuesta() {
        initComponents();
        setFrame();
    }

    private void setFrame() {
        listaVotaciones = new ArrayList<>();
        this.setTitle("Vota");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoEncuesta = new javax.swing.ButtonGroup();
        javax.swing.JLabel Pregunta = new javax.swing.JLabel();
        MainView = new javax.swing.JPanel();
        Si = new javax.swing.JRadioButton();
        No = new javax.swing.JRadioButton();
        Cancelar = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Estadisticas = new javax.swing.JMenu();
        ViewStats = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pregunta.setText("Debe dimitir pedro sánchez?");
        Pregunta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        MainView.setLayout(new java.awt.GridLayout(1, 0));

        GrupoEncuesta.add(Si);
        Si.setText("Si");
        Si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiActionPerformed(evt);
            }
        });
        MainView.add(Si);

        GrupoEncuesta.add(No);
        No.setText("No");
        MainView.add(No);

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        MainView.add(Cancelar);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        MainView.add(Aceptar);

        jPanel1.setLayout(new java.awt.GridLayout());

        jButton1.setText("Iniciar sesion");
        jPanel1.add(jButton1);

        jButton2.setText("Nuevo usuario");
        jPanel1.add(jButton2);

        Estadisticas.setText("Estadisticas");

        ViewStats.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_DOWN_MASK));
        ViewStats.setText("Ver");
        ViewStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewStatsActionPerformed(evt);
            }
        });
        Estadisticas.add(ViewStats);

        jMenuBar1.add(Estadisticas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Pregunta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MainView, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        if (!Si.isSelected() && !No.isSelected()) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar algo", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            listaVotaciones.add((Si.isSelected()) ? Respuesta.SI : Respuesta.NO);
            System.out.println("Borrar botones");
            GrupoEncuesta.clearSelection();
        }
    }//GEN-LAST:event_AceptarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CancelarActionPerformed

    private void SiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiActionPerformed

    private void ViewStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewStatsActionPerformed
        // TODO add your handling code here:
        recuentoVotos();
        StringBuilder msg = new StringBuilder(formatDateTimeStats());
        if (numVotos != 0) {
            msg.append(formatVoteStats());
        }
        JOptionPane.showConfirmDialog(this, msg, "Estadisticas", 0);
    }//GEN-LAST:event_ViewStatsActionPerformed
    private void recuentoVotos() {
        this.favorables = 0;
        this.contrarios = 0;
        this.numVotos = listaVotaciones.size();
        for (Respuesta voto : listaVotaciones) {
            if (voto == Respuesta.SI) {
                this.favorables++;
            } else {
                this.contrarios++;
            };
        }
    }

    private String formatDateTimeStats() {
        StringBuilder statsFormateados = new StringBuilder();
        Date fechaActual = new Date();
        SimpleDateFormat formateadorFecha = new SimpleDateFormat("dd' de 'MM' de 'yyyy");
        SimpleDateFormat formateadorHora = new SimpleDateFormat("HH':'mm':'ss");
        statsFormateados.append("Estamos a: ").append(formateadorFecha.format(fechaActual)).append('\n');
        statsFormateados.append("Son las: ").append(formateadorHora.format(fechaActual)).append('\n');
        statsFormateados.append("Hay un total de: ").append(numVotos).append(" votos\n");
        return statsFormateados.toString();

    }

    private String formatVoteStats() {
        StringBuilder statsFormateados = new StringBuilder();
        statsFormateados.append(favorables).append(" son a favor\n");
        statsFormateados.append(contrarios).append(" son en contra\n");
        return statsFormateados.toString();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEncuesta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEncuesta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JMenu Estadisticas;
    private javax.swing.ButtonGroup GrupoEncuesta;
    private javax.swing.JPanel MainView;
    private javax.swing.JRadioButton No;
    private javax.swing.JRadioButton Si;
    private javax.swing.JMenuItem ViewStats;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
