/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VentaCamisetas;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import VentaCamisetas.Tallas;
import java.util.ArrayList;
import javax.swing.SpinnerNumberModel;
import ventacamisetas.Ordenar;

/**
 *
 * @author goncalda
 */
public class GUITienda extends javax.swing.JFrame {

    private Color colCamiseta = Color.BLACK;
    private DefaultComboBoxModel<Tallas> modeloTallas;
    private SpinnerNumberModel modeloUnidadesCompradas;
    private ArrayList<Camiseta> listaCamisetas;
    /**
     * Creates new form GUITienda
     */
    public GUITienda() {
        initComponents();
        setFrame();
    }

    private void setFrame() {
        this.setTitle("Sara");
        this.setLocationRelativeTo(null);
        listaCamisetas= new ArrayList<>();
        modeloTallas = new DefaultComboBoxModel<>(Tallas.values());
        this.SelectorTalla.setModel(modeloTallas);
        modeloUnidadesCompradas = new SpinnerNumberModel(1, 1, 99, 1);
        this.SelectorUDS.setModel(modeloUnidadesCompradas);
        this.MuestraColor.setBackground(colCamiseta);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfiguradorCamiseta = new javax.swing.JPanel();
        SelectorTalla = new javax.swing.JComboBox<>();
        SelectorColor = new javax.swing.JButton();
        MuestraColor = new javax.swing.JLabel();
        Precio = new javax.swing.JLabel();
        SelectorUDS = new javax.swing.JSpinner();
        Unidades = new javax.swing.JLabel();
        Carrito = new javax.swing.JPanel();
        Finalizar = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        Cancelar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuOrdenar = new javax.swing.JMenu();
        jMenuItemAcendente = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ConfiguradorCamiseta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configura tu camiseta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(184, 134, 11))); // NOI18N

        SelectorColor.setText("Color");
        SelectorColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectorColorActionPerformed(evt);
            }
        });

        MuestraColor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MuestraColor.setOpaque(true);

        Precio.setText("Tallas");
        Precio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Unidades.setText("Unidades:");
        Unidades.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout ConfiguradorCamisetaLayout = new javax.swing.GroupLayout(ConfiguradorCamiseta);
        ConfiguradorCamiseta.setLayout(ConfiguradorCamisetaLayout);
        ConfiguradorCamisetaLayout.setHorizontalGroup(
            ConfiguradorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfiguradorCamisetaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ConfiguradorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SelectorTalla, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Precio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConfiguradorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Unidades, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SelectorUDS, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConfiguradorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MuestraColor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfiguradorCamisetaLayout.createSequentialGroup()
                        .addComponent(SelectorColor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        ConfiguradorCamisetaLayout.setVerticalGroup(
            ConfiguradorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfiguradorCamisetaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(ConfiguradorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ConfiguradorCamisetaLayout.createSequentialGroup()
                        .addGroup(ConfiguradorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Unidades, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectorColor))
                        .addGap(18, 18, 18)
                        .addGroup(ConfiguradorCamisetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectorUDS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectorTalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(MuestraColor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Finalizar.setText("Terminar");
        Finalizar.setToolTipText("Pulsa para finalizar la operacion");
        Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CarritoLayout = new javax.swing.GroupLayout(Carrito);
        Carrito.setLayout(CarritoLayout);
        CarritoLayout.setHorizontalGroup(
            CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarritoLayout.createSequentialGroup()
                .addGroup(CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cancelar)
                    .addComponent(Finalizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        CarritoLayout.setVerticalGroup(
            CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CarritoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CarritoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Finalizar)
                    .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuOrdenar.setText("Ordenar");

        jMenuItemAcendente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemAcendente.setText("Camisetas");
        jMenuItemAcendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcendenteActionPerformed(evt);
            }
        });
        jMenuOrdenar.add(jMenuItemAcendente);

        jMenuBar1.add(jMenuOrdenar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Carrito, javax.swing.GroupLayout.PREFERRED_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(ConfiguradorCamiseta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ConfiguradorCamiseta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Carrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectorColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectorColorActionPerformed
        System.out.println("Presionado");
        colCamiseta = JColorChooser.showDialog(this, "Elige el color de tu camiseta", colCamiseta);
        if (colCamiseta != null) {
            this.MuestraColor.setBackground(colCamiseta);
        }
    }//GEN-LAST:event_SelectorColorActionPerformed

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) && c != ',') {
            evt.consume();
        }
    }//GEN-LAST:event_jTextArea1KeyTyped

    private void FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarActionPerformed
        // TODO add your handling code here:
        try {
            if (!jTextArea1.getText().matches("^\\d+(?:[.,]\\d{1,2})?$")) {
            System.out.println("Formato de precio no valido");
        };
        } catch (Exception e) {
                        System.out.println("Precio vacio");

        }
        Camiseta camiseta = new Camiseta((Tallas) this.SelectorTalla.getSelectedItem());
        camiseta.setColores(colCamiseta);
        camiseta.setPvr(Double.parseDouble(this.jTextArea1.getText().replace(',','.')));
//        System.out.println("Insert Into");
//        System.out.println(camiseta);
        listaCamisetas.add(camiseta);
        System.out.println(listaCamisetas);
        
    }//GEN-LAST:event_FinalizarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_CancelarActionPerformed

    private void jMenuItemAcendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcendenteActionPerformed
            // TODO add your handling code here:
        Ordenar guiOrdenar = new Ordenar(this,true);
        guiOrdenar.setVisible(true);
            
    }//GEN-LAST:event_jMenuItemAcendenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITienda().setVisible(true);
            }
        });
    }

    public ArrayList<Camiseta> getListaCamisetas() {
        return listaCamisetas;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JPanel Carrito;
    private javax.swing.JPanel ConfiguradorCamiseta;
    private javax.swing.JButton Finalizar;
    private javax.swing.JLabel MuestraColor;
    private javax.swing.JLabel Precio;
    private javax.swing.JButton SelectorColor;
    private javax.swing.JComboBox<Tallas> SelectorTalla;
    private javax.swing.JSpinner SelectorUDS;
    private javax.swing.JLabel Unidades;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAcendente;
    private javax.swing.JMenu jMenuOrdenar;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}