select * from ALUM2425;
select DNI,NOMBRE,APELLIDOS,CURSO,NIVEL,CLASE FROM ALUM2425;
SELECT * FROM ALUM2425 WHERE POBLACION = 'GUADALAJARA';
SLECT DNI,NOMBRE,APELLIDOS, CURSO, NIVEL, CLASE FROM ALUM2425 ORDER BY APELLIDOS ASC, NOMBRE ASC;
SELECT NOMBRE FROM NOTAS_ALUMNOS WHERE NOTA1>7 AND (NOTA1,NOTA2,NOTA3)/3>6;
SELECT EJEMPLARES WHERE TEMA = 'LABORES';
SELECT EJEMPLARES WHERE TEMA LIKE 'LABORES';
SELECT TEMA, ESTANTE, EJEMPLARES WHERE EJEMPLARES BETWEEN(8,15);
SELECT TEMA, ESTANTE , EJEMPLARES WHERE EJEMPLARES NOT BETWEEN 'B'AND'D';
SELECT TEMA WHERE EJEMPLARES NOT BETWEEN 15 AND 20;


SELECT DISTINCT A.NOMBRE_ASIG
FROM ASIGNATURAS A
JOIN NOTAS N ON A.COD_ASIG = N.COD_ASIG
JOIN ALUMNOS AL ON AL.DNI = N.DNI
WHERE A.NOMBRE_ASIG LIKE '%o%o%o%'
  AND AL.POBLACION = 'Madrid';


SELECT NOMBRE_ASIG
FROM ASIGNATURAS
WHERE NOMBRE_ASIG LIKE '%o%o%o%'
  AND COD_ASIG IN (
        SELECT COD_ASIG
        FROM NOTAS
        WHERE DNI IN (
              SELECT DNI
              FROM ALUMNOS
              WHERE POBLACION = 'Madrid'
        )
  );


SELECT DISTINCT AL.NOMBRE, AL.APELLIDOS
FROM ALUMNOS AL
JOIN NOTAS N ON AL.DNI = N.DNI
WHERE AL.POBLACION = 'Madrid'
  AND N.NOTA < 5;


SELECT NOMBRE, APELLIDOS
FROM ALUMNOS
WHERE POBLACION = 'Madrid'
  AND DNI IN (
        SELECT DNI
        FROM NOTAS
        WHERE NOTA < 5
  );


SELECT DISTINCT AL.NOMBRE, AL.APELLIDOS
FROM ALUMNOS AL
JOIN NOTAS N ON AL.DNI = N.DNI
WHERE N.COD_ASIG = 1;


SELECT NOMBRE, APELLIDOS
FROM ALUMNOS
WHERE DNI IN (
      SELECT DNI
      FROM NOTAS
      WHERE COD_ASIG = 1
);


SELECT DISTINCT AL.NOMBRE, AL.APELLIDOS
FROM ALUMNOS AL
JOIN NOTAS N ON AL.DNI = N.DNI
JOIN ASIGNATURAS A ON A.COD_ASIG = N.COD_ASIG
WHERE A.NOMBRE_ASIG = 'FOL'
  AND N.NOTA BETWEEN 7 AND 8;


SELECT NOMBRE, APELLIDOS
FROM ALUMNOS
WHERE DNI IN (
      SELECT DNI
      FROM NOTAS
      WHERE NOTA BETWEEN 7 AND 8
        AND COD_ASIG = (
              SELECT COD_ASIG
              FROM ASIGNATURAS
              WHERE NOMBRE_ASIG = 'FOL'
        )
);