/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gf.local.Actividades.AlmacenCopia;

import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

/**
 *
 * @author goncalda
 */
public class GUIAlmacen extends javax.swing.JFrame {

    public static final String url = "jdbc:mysql://localhost:3306/almacen", user = "root", password = "";
    private DefaultComboBoxModel<TipoProducto> modComboTipoProd;
    private DefaultListModel<Producto> modListaProductos;
    private Connection con;

    /**
     * Creates new form GUIAlmacen
     */
    public GUIAlmacen() {
        initComponents();
        setFrame();
    }

    private void setFrame() {
        this.setPreferredSize(new Dimension(500, 500));
        this.setTitle("Manager de almacenes");
        pack();
        this.setLocationRelativeTo(null);
        //Cargar el combobox con los tipo de productos a partir de la select
        TipoProducto tipoDefault = new TipoProducto(-1, "Selecciona un producto");
        this.modComboTipoProd = new DefaultComboBoxModel<>();
        this.modComboTipoProd.addElement(tipoDefault);
        this.jComboBox1.setModel(modComboTipoProd);

        this.modListaProductos = new DefaultListModel<>();
        this.jList1.setModel(modListaProductos);

        try {
            this.con = DriverManager.getConnection(url, user, password);
            String sql = "select * from tiposproducto";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                TipoProducto tipoProducto = new TipoProducto(rs.getInt(1), rs.getString(2));
                this.modComboTipoProd.addElement(tipoProducto);
            }
        } catch (SQLException e) {
            System.out.println("Fallo al conectar");
        } finally {
            try {
                this.con.close();
            } catch (SQLException ex) {
                System.out.println("No cerada conexion");
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5));

        jLabel1.setText("Tipo de producto:");
        jPanel1.add(jLabel1);

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBox1PropertyChange(evt);
            }
        });
        jPanel1.add(jComboBox1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de productos"));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel2.add(jScrollPane1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        System.out.println(this.jComboBox1.getSelectedIndex());
        if (evt.getStateChange() == ItemEvent.SELECTED
                && this.jComboBox1.getSelectedIndex() != 0)
        {
            this.modListaProductos.clear();
            TipoProducto pBuscado= (TipoProducto) this.jComboBox1.getSelectedItem();
            ArrayList<Producto> productos = buscarProductoTipo(pBuscado);
            this.modListaProductos.addAll(productos);
            
        }
           
           


    }//GEN-LAST:event_jComboBox1ItemStateChanged
    
    
    
    private ArrayList<Producto> buscarProductoTipo(TipoProducto tipo) {
        ArrayList<Producto> lst=new ArrayList<>();
            this.modListaProductos.clear();
            try {
                this.con = DriverManager.getConnection(url, user, password);
                String sql = "select * from productos where idProducto = ?";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setInt(1, tipo.getIdTipo());
                
                ResultSet rs = ps.executeQuery(sql);
                while (rs.next()) {
                    Producto producto = new Producto(rs.getInt(1), rs.getString(2),rs.getDouble(3),rs.getInt(4),rs.getInt(5));
                    lst.add(producto);
                }
            } catch (SQLException e) {
                System.out.println("Fallo al conectar");
                System.out.println(e.getLocalizedMessage());
            } finally {
                try {
                    this.con.close();
                } catch (SQLException ex) {
                    System.out.println("No cerada conexion");
                }
            }

        
    
        return lst;
    }
    private void jComboBox1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBox1PropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBox1PropertyChange

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==2&&this.jList1.getSelectedValue()!=null) {
        Producto prodSeleccionado =this.jList1.getSelectedValue();
        int unidadesStock = prodSeleccionado.getCantidad();
        StringBuilder msg= new StringBuilder();
        msg.append("Stock en el almacen: ");
        msg.append(unidadesStock);
        
        
        
        }
    }//GEN-LAST:event_jList1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAlmacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAlmacen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<TipoProducto> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<Producto> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
